# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

 # Sitenizin üst menü yapılandırması
main:
  - name: "Director / Direktör"
    url: "/#about"
    weight: 10
  - name: "Our Team / Ekibimiz"
    url: "/#team"
    weight: 20
  - name: "Publications / Yayınlar"
    url: "/#papers"
    weight: 30
  - name: "Projects / Projeler"
    url: "projects/"
    weight: 40
  - name: "SOHE Life / Labdan Kareler"
    url: "/#news"
    weight: 50
  - name: "Talks / Etkinlikler"
    url: "/#talks"
    weight: 60
  - name: "Join Us / Bize Katılın"
    url: "/#join"
    weight: 70
