# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

 # Sitenizin üst menü yapılandırması
main:
  - name: "About / Hakkımda"
    url: "#about"
    weight: 10
    
  - name: "Publications / Yayınlar"
    url: "#publications"
    weight: 20

  - name: "Talks / Etkinlikler"
    url: "#talks"
    weight: 30

  - name: "News / Haberler"
    url: "#news"
    weight: 40

  - name: "Experience / Deneyim"
    url: "#experience"
    weight: 50

  - name: "Projects / Projeler"
    url: "#projects"
    weight: 60

  - name: "Courses / Dersler"
    url: "#courses"
    weight: 70
