# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

 # Sitenizin üst menü yapılandırması
main:
  - name: About / Hakkımda
    url: /
    weight: 10
  - name: Publications / Yayınlar
    url: /#papers
    weight: 15
  - name: Talks / Etkinlikler
    url: /#talks
    weight: 20
  - name: SOHE Life / Lab Çalışmaları
    url: /#news
    weight: 25
  - name: Projects / Projeler
    url: projects/
    weight: 35


